config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweeds#index"

  resources :users

  resources :tweeds

end

app/models/tweed.rb
class Tweed < ActiveRecord::Base
  validates :body, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweeds_controller.rb
class TweedsController < ApplicationController

  def index
    @tweeds = Tweed.all
  end


  def new
    @tweed = Tweed.new
  end

  def create
    @tweed = current_user.tweeds.new(tweed_params)
    if @tweed.save
      respond_to do |format|
        format.html do
          flash[:notice] = "You Tweed Posted. Jolly Good!"
          redirect_to tweeds_path
        end
        format.js
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = "Bloody hell."
          render :new
        end
        format.js { render js: "alert('fail');" }
      end
    end
  end

  def destroy
    @tweed = Tweed.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to tweeds_path }
      format.js
    end
  end

  private

    def tweed_params
      params.require(:tweed).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="navbar-brand" href="/">
         <%= image_tag 'cake.png' %>
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav pull-left">

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.email %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>

    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweedler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/flash' %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/tweeds/_form.html.erb
<%= bootstrap_form_for @tweed, remote: true do |f| %>
  <div class="form-group">
    <%= f.text_field :body %>
  </div>
  <%= f.submit "Don Tweed" %>
<% end %>

app/views/tweeds/_tweed.html.erb
<li class="well tweed" id="tweed_<%= tweed.id %>">
  <small>Tweed by <%= link_to tweed.user.email, user_path(tweed.user) %>:</small><br>
  <%= tweed.body %>
  <% if user_signed_in? && current_user == tweed.user %>
    <%= link_to '<span class="glyphicon glyphicon-trash pull-right"></span>'.html_safe, tweed_path(tweed), method: :delete, remote: true %>
  <% end %>
</li>

app/views/tweeds/create.js.erb
$('#new_tweed').remove();
$('#tweedify-btn').show();
$('#tweeds').prepend('<%= j render(@tweed) %>');
$('#tweed_<%= @tweed.id %>').hover(function () {
  $(this).find('.glyphicon').show();
}, function() {
   $(this).find('.glyphicon').hide();
});

app/views/tweeds/destroy.js.erb
$('#tweed_<%= @tweed.id %>').remove();

app/views/tweeds/index.html.erb
<% if user_signed_in? %>
  <%= link_to "Tweedify", new_tweed_path, class: "btn btn-info", id: "tweedify-btn", remote: true %>
<% end %>

<ul class="list-unstyled" id="tweeds">
  <%= render @tweeds.reverse %>
</ul>

app/views/tweeds/new.html.erb
<% if user_signed_in? %>

<%= render 'form' %>

<% else %>
<p>Sign in to tweed.</p>
<% end %>

app/views/tweeds/new.js.erb
$('#tweedify-btn').hide().after('<%= j render("form") %>');

app/views/users/index.html.erb
<ul class="list-unstyled">
  <% @users.each do |user| %>
    <li><%= link_to user.email, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
  <h2><%= @user.email %></h2>